algo = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(algo))
print('É alfanumerico? ', algo.isalnum())
print('É só espaços? ', algo.isspace())
print('É numerico? ', algo.isnumeric())
print('É alfabeto? ', algo.isalpha())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
print('Está capitalizada? ', algo.istitle())
